"""Build a small sample employee SQLite database.

This database is intended for MCP demos where tools read from a local,
project-owned data source instead of a public internet API.

Usage:
  python scripts/build_employees_db.py --db data/employees.db
"""

import argparse
import os
import sqlite3


EMPLOYEES = [
    (
        "E0001",
        "愛子",
        "田中",
        "aiko.tanaka@example.test",
        "+81-3-5550-0101",
        "経営企画部",
        "代表取締役社長",
        "正社員",
        "東京本社",
        "2016-04-01",
        None,
        "在籍中",
    ),
    (
        "E0002",
        "健二",
        "佐藤",
        "kenji.sato@example.test",
        "+81-3-5550-0102",
        "開発部",
        "開発部長",
        "正社員",
        "東京本社",
        "2017-06-12",
        "E0001",
        "在籍中",
    ),
    (
        "E0003",
        "美香",
        "鈴木",
        "mika.suzuki@example.test",
        "+81-3-5550-0103",
        "営業部",
        "営業部長",
        "正社員",
        "東京本社",
        "2018-01-15",
        "E0001",
        "在籍中",
    ),
    (
        "E0004",
        "大地",
        "山田",
        "daichi.yamada@example.test",
        "+81-3-5550-0104",
        "人事部",
        "人事マネージャー",
        "正社員",
        "東京本社",
        "2018-09-03",
        "E0001",
        "在籍中",
    ),
    (
        "E0005",
        "花",
        "小林",
        "hana.kobayashi@example.test",
        "+81-6-5550-0201",
        "経理部",
        "経理マネージャー",
        "正社員",
        "大阪支社",
        "2019-02-18",
        "E0001",
        "在籍中",
    ),
    (
        "E0006",
        "太郎",
        "中村",
        "taro.nakamura@example.test",
        "+81-3-5550-0111",
        "開発部",
        "バックエンドエンジニア",
        "正社員",
        "東京本社",
        "2019-05-07",
        "E0002",
        "在籍中",
    ),
    (
        "E0007",
        "結衣",
        "伊藤",
        "yui.ito@example.test",
        "+81-3-5550-0112",
        "開発部",
        "フロントエンドエンジニア",
        "正社員",
        "東京本社",
        "2020-03-16",
        "E0002",
        "在籍中",
    ),
    (
        "E0008",
        "空",
        "渡辺",
        "sora.watanabe@example.test",
        "+81-45-5550-0301",
        "開発部",
        "SREエンジニア",
        "正社員",
        "横浜オフィス",
        "2020-07-01",
        "E0002",
        "在籍中",
    ),
    (
        "E0009",
        "芽衣",
        "高橋",
        "mei.takahashi@example.test",
        "+81-3-5550-0113",
        "開発部",
        "QAエンジニア",
        "正社員",
        "東京本社",
        "2021-01-12",
        "E0002",
        "在籍中",
    ),
    (
        "E0010",
        "陸",
        "加藤",
        "riku.kato@example.test",
        "+81-3-5550-0114",
        "開発部",
        "データエンジニア",
        "正社員",
        "東京本社",
        "2021-04-05",
        "E0002",
        "在籍中",
    ),
    (
        "E0011",
        "奈々",
        "吉田",
        "nana.yoshida@example.test",
        "+81-6-5550-0211",
        "プロダクト部",
        "プロダクトマネージャー",
        "正社員",
        "大阪支社",
        "2019-10-21",
        "E0002",
        "在籍中",
    ),
    (
        "E0012",
        "陽翔",
        "山本",
        "haruto.yamamoto@example.test",
        "+81-6-5550-0212",
        "プロダクト部",
        "UXデザイナー",
        "正社員",
        "大阪支社",
        "2020-11-09",
        "E0011",
        "在籍中",
    ),
    (
        "E0013",
        "莉奈",
        "森",
        "rina.mori@example.test",
        "+81-92-5550-0401",
        "営業部",
        "アカウント営業",
        "正社員",
        "福岡支社",
        "2019-07-22",
        "E0003",
        "在籍中",
    ),
    (
        "E0014",
        "海斗",
        "井上",
        "kaito.inoue@example.test",
        "+81-3-5550-0121",
        "営業部",
        "アカウント営業",
        "正社員",
        "東京本社",
        "2020-02-03",
        "E0003",
        "在籍中",
    ),
    (
        "E0015",
        "彩",
        "木村",
        "aya.kimura@example.test",
        "+81-6-5550-0221",
        "営業部",
        "営業企画担当",
        "正社員",
        "大阪支社",
        "2021-08-17",
        "E0003",
        "在籍中",
    ),
    (
        "E0016",
        "蓮",
        "林",
        "ren.hayashi@example.test",
        "+81-92-5550-0402",
        "カスタマーサクセス部",
        "カスタマーサクセスマネージャー",
        "正社員",
        "福岡支社",
        "2020-06-29",
        "E0003",
        "在籍中",
    ),
    (
        "E0017",
        "美緒",
        "清水",
        "mio.shimizu@example.test",
        "+81-3-5550-0131",
        "カスタマーサクセス部",
        "サポート担当",
        "正社員",
        "東京本社",
        "2021-12-01",
        "E0016",
        "在籍中",
    ),
    (
        "E0018",
        "陽菜",
        "斎藤",
        "hinata.saito@example.test",
        "+81-45-5550-0302",
        "マーケティング部",
        "マーケティングマネージャー",
        "正社員",
        "横浜オフィス",
        "2019-11-11",
        "E0003",
        "在籍中",
    ),
    (
        "E0019",
        "優奈",
        "松本",
        "yuna.matsumoto@example.test",
        "+81-45-5550-0303",
        "マーケティング部",
        "コンテンツ担当",
        "パートタイム",
        "横浜オフィス",
        "2022-03-14",
        "E0018",
        "在籍中",
    ),
    (
        "E0020",
        "颯太",
        "山崎",
        "sota.yamazaki@example.test",
        "+81-3-5550-0141",
        "経理部",
        "経理担当",
        "正社員",
        "東京本社",
        "2020-09-23",
        "E0005",
        "在籍中",
    ),
    (
        "E0021",
        "明里",
        "石川",
        "akari.ishikawa@example.test",
        "+81-6-5550-0231",
        "経理部",
        "給与計算担当",
        "正社員",
        "大阪支社",
        "2021-06-07",
        "E0005",
        "在籍中",
    ),
    (
        "E0022",
        "亮太",
        "前田",
        "ryota.maeda@example.test",
        "+81-3-5550-0151",
        "人事部",
        "採用担当",
        "正社員",
        "東京本社",
        "2020-01-20",
        "E0004",
        "在籍中",
    ),
    (
        "E0023",
        "心",
        "藤田",
        "kokoro.fujita@example.test",
        "+81-3-5550-0152",
        "人事部",
        "研修コーディネーター",
        "パートタイム",
        "東京本社",
        "2022-04-18",
        "E0004",
        "在籍中",
    ),
    (
        "E0024",
        "悠人",
        "小川",
        "yuto.ogawa@example.test",
        "+81-45-5550-0304",
        "開発部",
        "モバイルエンジニア",
        "正社員",
        "横浜オフィス",
        "2022-07-04",
        "E0002",
        "在籍中",
    ),
    (
        "E0025",
        "乃愛",
        "後藤",
        "noa.goto@example.test",
        "+81-3-5550-0115",
        "開発部",
        "セキュリティエンジニア",
        "正社員",
        "東京本社",
        "2022-10-03",
        "E0002",
        "在籍中",
    ),
    (
        "E0026",
        "駿",
        "岡田",
        "shun.okada@example.test",
        "+81-92-5550-0403",
        "カスタマーサクセス部",
        "テクニカルサポートエンジニア",
        "正社員",
        "福岡支社",
        "2022-12-12",
        "E0016",
        "在籍中",
    ),
    (
        "E0027",
        "真央",
        "長谷川",
        "mao.hasegawa@example.test",
        "+81-6-5550-0241",
        "プロダクト部",
        "プロダクトアナリスト",
        "正社員",
        "大阪支社",
        "2023-02-06",
        "E0011",
        "在籍中",
    ),
    (
        "E0028",
        "樹",
        "村上",
        "itsuki.murakami@example.test",
        "+81-3-5550-0122",
        "営業部",
        "インサイドセールス担当",
        "契約社員",
        "東京本社",
        "2023-04-10",
        "E0003",
        "在籍中",
    ),
    (
        "E0029",
        "咲",
        "近藤",
        "saki.kondo@example.test",
        "+81-45-5550-0305",
        "マーケティング部",
        "需要創出担当",
        "正社員",
        "横浜オフィス",
        "2023-05-22",
        "E0018",
        "在籍中",
    ),
    (
        "E0030",
        "隼人",
        "石井",
        "hayato.ishii@example.test",
        "+81-3-5550-0116",
        "開発部",
        "機械学習エンジニア",
        "正社員",
        "東京本社",
        "2023-08-01",
        "E0002",
        "在籍中",
    ),
    (
        "E0031",
        "夏希",
        "阿部",
        "natsuki.abe@example.test",
        "+81-6-5550-0242",
        "プロダクト部",
        "テクニカルライター",
        "契約社員",
        "大阪支社",
        "2023-09-19",
        "E0011",
        "在籍中",
    ),
    (
        "E0032",
        "拓海",
        "遠藤",
        "takumi.endo@example.test",
        "+81-92-5550-0404",
        "カスタマーサクセス部",
        "導入コンサルタント",
        "正社員",
        "福岡支社",
        "2023-11-06",
        "E0016",
        "在籍中",
    ),
    (
        "E0033",
        "葵",
        "福田",
        "aoi.fukuda@example.test",
        "+81-3-5550-0153",
        "人事部",
        "HRビジネスパートナー",
        "正社員",
        "東京本社",
        "2024-01-15",
        "E0004",
        "在籍中",
    ),
    (
        "E0034",
        "湊",
        "三浦",
        "minato.miura@example.test",
        "+81-3-5550-0117",
        "開発部",
        "開発インターン",
        "インターン",
        "東京本社",
        "2024-04-01",
        "E0002",
        "在籍中",
    ),
    (
        "E0035",
        "莉央",
        "中島",
        "rio.nakajima@example.test",
        "+81-6-5550-0222",
        "営業部",
        "パートナー営業",
        "正社員",
        "大阪支社",
        "2024-06-03",
        "E0003",
        "在籍中",
    ),
    (
        "E0036",
        "朝陽",
        "太田",
        "asahi.ota@example.test",
        "+81-45-5550-0306",
        "マーケティング部",
        "マーケティングインターン",
        "インターン",
        "横浜オフィス",
        "2024-07-01",
        "E0018",
        "在籍中",
    ),
]


def build(db_path: str) -> None:
    os.makedirs(os.path.dirname(db_path) or ".", exist_ok=True)
    if os.path.exists(db_path):
        os.remove(db_path)

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.executescript(
        """
        PRAGMA foreign_keys = ON;

        CREATE TABLE employees (
            employee_id     TEXT PRIMARY KEY,
            first_name      TEXT NOT NULL,
            last_name       TEXT NOT NULL,
            email           TEXT NOT NULL UNIQUE,
            phone           TEXT NOT NULL,
            department      TEXT NOT NULL,
            job_title       TEXT NOT NULL,
            employment_type TEXT NOT NULL,
            office_location TEXT NOT NULL,
            hire_date       TEXT NOT NULL,
            manager_id      TEXT,
            status          TEXT NOT NULL,
            FOREIGN KEY (manager_id) REFERENCES employees(employee_id)
        );

        CREATE INDEX idx_employees_department ON employees(department);
        CREATE INDEX idx_employees_office_location ON employees(office_location);
        CREATE INDEX idx_employees_manager_id ON employees(manager_id);
        CREATE INDEX idx_employees_status ON employees(status);
        """
    )

    cur.executemany(
        """
        INSERT INTO employees (
            employee_id, first_name, last_name, email, phone,
            department, job_title, employment_type, office_location,
            hire_date, manager_id, status
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        EMPLOYEES,
    )

    conn.commit()
    count = cur.execute("SELECT COUNT(*) FROM employees").fetchone()[0]
    conn.close()

    print(f"[OK] {db_path}")
    print(f"     employees: {count} rows")


def main() -> None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description="Build sample employee SQLite DB")
    parser.add_argument("--db", default=os.path.join(here, "data", "employees.db"))
    args = parser.parse_args()
    build(args.db)


if __name__ == "__main__":
    main()
